server:
#  port: 0
  port: 8080

spring:
  application:
    name: "store-service"
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: user
    password: password

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8082/eureka

